module.exports = {
    LOGIN_PAGE: 'https://play.qobuz.com/login',
    LOGGED_IN_CHECK: 'div.user-avatar',
    INPUT_USERNAME: 'input[name=login]',
    INPUT_PASSWORD: 'input[type=password]',
    PLAYLIST: 'https://play.qobuz.com/playlist/2058525',
    PLAY_BUTTON: '.pct.pct-play.item-button',
    LOGIN_BUTTON: 'button[type=submit]',
    SKIP_BUTTON: '.pct.pct-player-next.cpointer',
    PAUSE_BUTTON: '.pct.pct-player-pause.cpointer',
    RANDOM_BUTTON: 'div.item-buttons > a > .pct-shuffle',
    RANDOM_BUTTON_ACTIVATED: '.pct.pct-shuffle.cpointer.c2',
    LOOP_BUTTON: '.pct.pct-repeat.cpointer',
    LOOP_BUTTON_ACTIVATED: '.pct.pct-repeat.cpointer.c2',
}
