FROM zenato/puppeteer
USER root
RUN apt update && apt install -y apt-utils xvfb
RUN npm install ssl-root-cas puppeteer-extra puppeteer-extra-plugin-stealth puppeteer-extra-plugin-flash sync-request random-useragent
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install ./google-chrome-stable_current_amd64.deb
WORKDIR /home
